### ISSUE TITLE
Import error when upgrading to django_otp 0.3.2

### ISSUE THREAD

**Issue by troygrosfield** [Bouke/django-two-factor-auth#123]
Everything worked fine with django_otp version 0.3.1. Then when upgrading to 0.3.2, I see the following error:

```py
File "/py34/lib/python3.4/site-packages/two_factor/models.py", line 9, in <module>
    from django_otp import Device
ImportError: cannot import name 'Device'
```

The original error can be seen here along with the django_otp author's comments:

- https://bitbucket.org/psagers/django-otp/issues/9/importerror-cannot-import-name-device

**Comment by Bouke** [comment]
This has already been resolved in master (04a09fa60134b72687a129a3cd1f3e553cd6ed7d). I've just published a patch release (1.2.1) as an intermediate fix.
