### ISSUE TITLE
Migrations fail on django 1.7.0 due to preserve_default

### ISSUE THREAD

**Issue by VincentVW** [Bouke/django-two-factor-auth#83]
Don't know about earlier versions, but on Django 1.7.0 migrations fail due to the preserve_default argument on migration 0002_auto_20150110_0810;

__init__() got an unexpected keyword argument 'preserve_default'

Cause:

preserve_default argument was added in Django 1.7.1. No backward compatibility apparently :? 

https://docs.djangoproject.com/en/1.7/ref/migration-operations/#alterfield

**Comment by VincentVW** [comment]
Btw; works fine on 1.7.1 and onwards

**Comment by Bouke** [comment]
Removing `preserve_default` from the migration should resolve this issue. The current value `True` is also the default, so no issues there as well. Although running Django 1.7.0 is discouraged, as you should always run the latest minor version because of security patches.

**Comment by avkpol** [comment]
Thanks, it works
