### ISSUE TITLE
error with random_hex

### ISSUE THREAD

**Issue by skuflow** [Bouke/django-two-factor-auth#340]
We are seeing an error about random_hex.  We are using a MSSQL database if that makes a difference.  The error is:

 _**File "[snipped]\Python\Python38-32\lib\site-packages\two_factor\views\core.py", line 357, in get_key
    key = random_hex(20).decode('ascii')
AttributeError: 'str' object has no attribute 'decode'**_

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

We cannot login to the admin area or really collect static (without errors) at this point.

## Your Environment

* Browser and version: any
* Python version: 3.8
* Django version: 2.2
* django-otp version: latest stable via pip
* django-two-factor-auth version: latest stable via pip
* Link to your project: n/a

**Comment by bedubs** [comment]
I had this same issue today after upgrading the django-otp from 0.7.5 to 0.8.1 (latest stable). Changing back to 0.7.5 resolved the issue. This was the case on Django 2.2 and 3.0.3.

**Comment by skuflow** [comment]
Thanks for the info.  May give that a shot.

**Comment by moggers87** [comment]
Duplicate of #335
