### ISSUE TITLE
django-two-factor-auth - does not work on django 1.11rc1

### ISSUE THREAD

**Issue by pypetey** [Bouke/django-two-factor-auth#199]
from django release docs:
The undocumented django.utils.functional.lazy_property is removed.

```
    from django.utils.functional import lazy_property
    ImportError: cannot import name 'lazy_property'
```

**Comment by Bouke** [comment]
Already fixed in master: #195
